name: myDiscordReward
version: '${project.version}'
main: me.zombix.mydiscordreward.MyDiscordReward
api-version: '1.16'
authors: [Zombix3000]
description: Plugin for reward by join discord
commands:
  mydiscordreward:
    description: myDiscordReward plugin command
    usage: /mydiscordreward <reload/update/addrewarditem/addrewardcommand> (command)
    aliases: [mdcr]

permissions:
  mydiscordreward.mydiscordreward:
    description: Allow to use /mydiscordreward
    default: true
  mydiscordreward.getreward:
    description: Allow to get reward
    default: true
  mydiscordreward.admin:
    description: Allow to use /mydiscordreward <reload/update/addrewarditem/addrewardcommand>
    default: op