######################################
# --- myDiscordReward v1.0 Plugin --- #
######################################

#This is a config for myDiscordReward plugin!
#More info you can find in plugin documentation or in our discord: https://discord.gg/qTpgQXQZye

#Plugin should checking for new updates
check-for-updates: true

bot-token: "nope"

reward:
  commands:
  items:
